Style updates to card course component
unimelb/pattern-lib pull request #1578
Opened 2021-04-08 06:21 UTC by lmounsey

# Description

This includes style updates to the `CardCourse` component, as well as alternative styling as a search result, which highlights matching text within the name. This util function will be used on another future component.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [ ] Make sure to do not repeat yourself (DRY)
- [ ] Snapshots tested
- [ ] A11y tested
- [ ] CSS utilises BEM naming convention and structure
- [ ] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [ ] Crossbrowser testing (IE11, Safari 8+, iOS 8.4+, Android 4.4+, Firefox ESR (v52.x), iPhone (4s,6), iPad 2, Galaxy s5) 
- [ ] My changes generate no new warnings
- [ ] I have added tests (e2e and unit) that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Added the new component to the index.js (Vue and Lib) export

# Reviewer Checklist

- [ ] Code is not repeated (DRY)
- [ ] ES6+ code is used where possible
- [ ] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [ ] CSS utilises BEM naming convention and structure
- [ ] Snapshots tested against a copy of dev snapshots to check UI changes are intended
- [ ] A11y tested
- [ ] Crossbrowser tested in at least IE11

2021-04-08 06:21 UTC, gepifanio commented
Comment: Deploy Started

Building with commit 8dc1dcf5d9c0cdf03aeed639c4946410511b0e59

https://app.netlify.com/sites/pattern-lib-unimelb/deploys/606ea0fee32b9c00079abc88

2021-04-08 06:47 UTC, gepifanio commented on components/cards/_card-course.css
> +    top: -1px;
please use rem instead of px

2021-04-08 06:49 UTC, gepifanio requested changes
Hey @lmounsey, It looks good for me, just wondering if you could add a new variation in the storybook showing the card with the search query prop activating it, just to exemplify for the people how to use it, you could use the existing story to add a new card with the prop as well.

2021-04-08 06:49 UTC, gepifanio commented on components/cards/_card-course.css
> +    top: -1px;
please use rem instead of px

2021-04-08 06:49 UTC, gepifanio commented on components/cards/_card-course.css
> +    border-top-left-radius: 2px;
please use rem instead of px

2021-04-27 23:49 UTC, lmounsey commented on components/cards/_card-course.css
> +    top: -1px;
Updated this to use rems

2021-04-27 23:49 UTC, lmounsey commented on components/cards/_card-course.css
> +    border-top-left-radius: 2px;
Updated this to use rems

2021-04-28 07:55 UTC, gepifanio approved these changes
looks good just needs to fix the test

2021-04-28 23:45 UTC, lmounsey commented
> looks good just needs to fix the test

Yep - test should be fixed now!

2021-04-29 01:59 UTC, jaredh-um approved these changes

2021-04-29 03:36 UTC, merged