Feature/page footer today
unimelb/pattern-lib pull request #1598
Opened 2021-05-03 07:52 UTC by lmounsey

# Description

New page footer component for the update home page design from Today agency. 

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [ ] Make sure to do not repeat yourself (DRY)
- [ ] Snapshots tested
- [ ] A11y tested
- [ ] CSS utilises BEM naming convention and structure
- [ ] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [ ] Crossbrowser testing (IE11, Safari 8+, iOS 8.4+, Android 4.4+, Firefox ESR (v52.x), iPhone (4s,6), iPad 2, Galaxy s5) 
- [ ] My changes generate no new warnings
- [ ] I have added tests (e2e and unit) that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Added the new component to the index.js (Vue and Lib) export

# Reviewer Checklist

- [ ] Code is not repeated (DRY)
- [ ] ES6+ code is used where possible
- [ ] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [ ] CSS utilises BEM naming convention and structure
- [ ] Snapshots tested against a copy of dev snapshots to check UI changes are intended
- [ ] A11y tested
- [ ] Crossbrowser tested in at least IE11

2021-05-03 07:58 UTC, gepifanio commented
Comment: Deploy Started

Building with commit 70032fb7d6713fdbc3e54bd60aba48281aed6967

https://app.netlify.com/sites/pattern-lib-unimelb/deploys/608fabac2f33d90007b8a1c8

2021-05-04 01:22 UTC, gepifanio requested changes
we have 2 separete build targets in the project,

1: Which is the file `targets/lib/index.js` targeting as a library which the CMS would use, the components needs to be exported there to be available.
2: Which is the file: `targets/vue/index.js` targeting vue (SPA) which the FAC would use, the components needs to be exported there to be available.

2021-05-04 01:22 UTC, gepifanio commented on components/footer/PageFooterToday.vue
> +    return {
Could you change to accept the links data via `props` as well, and set the default as is.

So if the data come through via prop use the props, otherwise use the `fallback` default we have now.

2021-05-04 03:31 UTC, jaredh-um requested changes
Hi Lucas,

Looking good. My feedback:
- [ ] Reconciliation link currently going to `https://unimelb.edu.au/reconciliation` which redirects to `https://about.unimelb.edu.au/reconciliation`. Please adjust link to use the endpoint rather than the redirect (we need to update this in the old footer too)
- [x] 'Online terms and privacy' page at `https://www.unimelb.edu.au/legal` is being referred to as 'Disclaimer and copyright' in the new footer. This was only recently changed on our existing footer as per [this issue](https://github.com/unimelb/pattern-lib/issues/1545)
- [x] Grid additions - can the suffixes be changed from `-today` to something more descriptive? Doesn't lend itself to intuitive re-use as-is
- [ ] Can `-today` suffix in footer CSS be amended to `-2021` or something more generic?

2021-05-04 04:06 UTC, gepifanio reviewed
As I could notice, you been adding `CSS` and scoping the parent element and applying styling to the element itself without any class for example: 

```css
  &__secondary-links {
    li {
      margin-bottom: 1.5rem;
    }

    a {
      color: rgb(var(--col-white));
    }
  }
```

As we are sort in a rush its ok to leave this one as is, but for the future please add classes to element and style the class and not the element, just to keep consistent with our code base, also not to tidy the styling to the element, in case we need to change the element we dont have to touch the CSS. 
Example: 

```css
  &__secondary-links {
    &-blabla {
      margin-bottom: 1.5rem;
    }

    &-lala {
      color: rgb(var(--col-white));
    }
  }
```

2021-05-04 05:42 UTC, lmounsey commented on components/footer/PageFooterToday.vue
> +    return {
Done!

2021-05-04 05:45 UTC, lmounsey commented
Hey @gepifanio and @jaredh-um 

I've made those fixes requested. 

I've changed the grid to use a `--lg` modifier instead. RE: the component name `PageFooterToday` to `PageFooter2021` - happy to change that based on your recommendations here - There's going to quite a few components that are slight variations of existing ones, so would be good to come up with a pattern I can replicate as I introduce more components

2021-05-05 04:19 UTC, gepifanio approved these changes
Looks good

2021-05-05 05:24 UTC, jaredh-um commented
> Hey @gepifanio and @jaredh-um
> 
> I've made those fixes requested.
> 
> I've changed the grid to use a `--lg` modifier instead. RE: the component name `PageFooterToday` to `PageFooter2021` - happy to change that based on your recommendations here - There's going to quite a few components that are slight variations of existing ones, so would be good to come up with a pattern I can replicate as I introduce more components

Hey Lucas, if you can just use `2021` for that kind of thing for this component and going forward, that would be ideal, thanks.

2021-05-05 06:21 UTC, jaredh-um approved these changes
👍 Looks good

2021-05-05 06:22 UTC, lmounsey commented
This one is hopefully good to go now - a little caveat - the HTML reference of the component is coming through as `<page-footer2021></page-footer2021>`

Thought it might be `page-footer-2021` but perhaps the number is throwing off the kebab case. Not sure if this an issue as long as it's documented correctly.

2021-05-10 00:19 UTC, gepifanio requested changes
I forgot to ask and mention before, but could you please also add unit testing for the component, you could follow the same example like this one I am doing for the PathfinderToday:

```

import {
  shallow,
} from 'vue-test-utils';
import { axe, toHaveNoViolations } from 'jest-axe';
import PathfinderToday from '../PathfinderToday.vue';

expect.extend(toHaveNoViolations);

const pathfinderLinks = [
  {
    title: 'Undergraduate courses',
    description: 'Flexible first degrees that you can tailor to your career goals, or explore new possibilities.',
    href: '/landing-page/',
  },
  {
    title: 'Graduate courses',
    description: 'Study in small classes led by experts alongside others who share your interests and goals.',
    href: '/landing-page/',
  },
  {
    title: 'Graduate research',
    description: 'Access dedicated research centres, advanced  facilities, generous scholarships and more.',
    href: '/landing-page/',
  },
  {
    title: 'Short&nbsp;courses&nbsp;and microcredentials',
    description: 'Upskill, expand your knowledge and take the next step in your career with focused courses.',
    href: '/landing-page/',
  },
];

describe('PathfinderToday', () => {
  it('should match snapshot', () => {
    const result = shallow(PathfinderToday, {
      propsData: {
        items: pathfinderLinks,
      },
    }).element;
    expect(result).toMatchSnapshot();
  });

  it('Component throws no accessibility violations', (done) => {
    const html = shallow(PathfinderToday, {
      propsData: {
        items: pathfinderLinks,
      },
    }).html();
    // pass anything that outputs html to axe
    return axe(html).then((response) => {
      expect(response).toHaveNoViolations();
      done();
    });
  });
});
```

2021-05-11 04:51 UTC, gepifanio approved these changes

2021-05-12 00:39 UTC, jaredhenderson commented
Updated Storybook preview link in PR description.

2021-05-12 04:37 UTC, angieraj commented
@anormand can you please review - preview link has been updated

2021-05-12 05:16 UTC, anormand commented
This component passes testing using Chrome + Voiceover on Mac and Chrome + NVDA on PC

2021-05-12 06:05 UTC, merged