Add new video components and new icon for play button
unimelb/pattern-lib pull request #1599
Opened 2021-05-04 02:42 UTC by lmounsey

# Description

New components added - `Video` and `VideoFullWidth`. Have documented these in Storybook and detailed how to use them.

I've also added another icon `play-circle` as well. 

Happy yo take your guidance on naming convention of the component here - wasn't sure if should sit with the embed stuff or be seperate.

Also, I don't have any good example assets yet of the 'Portrait' video with an autoloop, so it's still referring to then Brown assets - if this is an issue, do you have any placeholder assets I could be pointing to?

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [ ] Make sure to do not repeat yourself (DRY)
- [ ] Snapshots tested
- [ ] A11y tested
- [ ] CSS utilises BEM naming convention and structure
- [ ] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [ ] Crossbrowser testing (IE11, Safari 8+, iOS 8.4+, Android 4.4+, Firefox ESR (v52.x), iPhone (4s,6), iPad 2, Galaxy s5) 
- [ ] My changes generate no new warnings
- [ ] I have added tests (e2e and unit) that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Added the new component to the index.js (Vue and Lib) export

# Reviewer Checklist

- [ ] Code is not repeated (DRY)
- [ ] ES6+ code is used where possible
- [ ] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [ ] CSS utilises BEM naming convention and structure
- [ ] Snapshots tested against a copy of dev snapshots to check UI changes are intended
- [ ] A11y tested
- [ ] Crossbrowser tested in at least IE11

2021-05-04 02:42 UTC, gepifanio commented
Comment: Deploy Started

Building with commit fc9c9ff71b152180f5325aab3d6b650b7a7f774f

https://app.netlify.com/sites/pattern-lib-unimelb/deploys/6090b48e5806d500083907ce

2021-05-04 04:02 UTC, jaredh-um approved these changes
Hi Lucas,

Looks good to me. I will leave it to Gui regarding the naming conventions and location. We should definitely remove the external asset links as soon as we have our own example though.

Edit: Added alternative URLs for those assets

2021-05-04 04:09 UTC, gepifanio requested changes

2021-05-04 04:09 UTC, gepifanio commented on components/video/stories/video.md
> +  poster="{ src: 'https://picsum.photos/seed/1/540/360', alt: ' }"
alt prop has a typo, is missing one more `'`

2021-05-04 04:09 UTC, gepifanio commented on targets/lib/index.js
> +Vue.component('video', Video);
good one also needed to be added to the vue build process as well: `targets/vue/index.js`

2021-05-04 04:10 UTC, gepifanio commented
> Hi Lucas,
> 
> Looks good to me. I will leave it to Gui regarding the naming conventions and location. We should definitely remove the Brown link as soon as we have our own example though.

Regarding the stories folder, would be better to keep consistent and add the stories under the `Embed` folder.

2021-05-04 04:17 UTC, jaredh-um commented on components/video/stories/VideoPortrait.vue
> +      src: 'https://www.brown.edu/sites/g/files/dprerj316/files/styles/portrait_sfts_desktop/public/Byrd_Advice.jpg?h=30f5acd3&itok=hcyHpFiN',
Please replace this URL with the temporary placeholder: 
`https://study.unimelb.edu.au/__data/assets/image/0021/265404/Byrd_Advice.jpg`

2021-05-04 04:18 UTC, jaredh-um commented on components/video/stories/VideoPortrait.vue
> +      preview: 'https://player.vimeo.com/external/336863136.sd.mp4?s=234cbb2adf6f8c523093bc0627e7d8bdb697db94&amp;profile_id=165',
Please replace this URL with the temporary placeholder:
`https://study.unimelb.edu.au/__data/assets/file/0022/265405/Byrd_Video.mp4`

2021-05-04 05:55 UTC, gepifanio requested changes

2021-05-04 05:55 UTC, gepifanio commented on components/embed/Video.vue
> +      const additionalParams = this.videoApi ? `&enablejsapi=1&origin=https%3A%2F%2F${document.location.hostname}.unimelb.edu.au` : '';
- [ ] Please remove the `unimelb.edu.au` as the `hostname` will already have the unimelb domain and that will include any subdomain as well.

2021-05-04 07:24 UTC, lmounsey commented on components/embed/Video.vue
> +      const additionalParams = this.videoApi ? `&enablejsapi=1&origin=https%3A%2F%2F${document.location.hostname}.unimelb.edu.au` : '';
This should be fixed now

2021-05-05 05:05 UTC, gepifanio approved these changes
Looks good

2021-05-05 05:21 UTC, jaredh-um approved these changes
Looks good 👍

2021-05-10 00:19 UTC, gepifanio requested changes
I forgot to ask and mention before, but could you please also add unit testing for the component, you could follow the same example like this one I am doing for the PathfinderToday:

```

import {
  shallow,
} from 'vue-test-utils';
import { axe, toHaveNoViolations } from 'jest-axe';
import PathfinderToday from '../PathfinderToday.vue';

expect.extend(toHaveNoViolations);

const pathfinderLinks = [
  {
    title: 'Undergraduate courses',
    description: 'Flexible first degrees that you can tailor to your career goals, or explore new possibilities.',
    href: '/landing-page/',
  },
  {
    title: 'Graduate courses',
    description: 'Study in small classes led by experts alongside others who share your interests and goals.',
    href: '/landing-page/',
  },
  {
    title: 'Graduate research',
    description: 'Access dedicated research centres, advanced  facilities, generous scholarships and more.',
    href: '/landing-page/',
  },
  {
    title: 'Short&nbsp;courses&nbsp;and microcredentials',
    description: 'Upskill, expand your knowledge and take the next step in your career with focused courses.',
    href: '/landing-page/',
  },
];

describe('PathfinderToday', () => {
  it('should match snapshot', () => {
    const result = shallow(PathfinderToday, {
      propsData: {
        items: pathfinderLinks,
      },
    }).element;
    expect(result).toMatchSnapshot();
  });

  it('Component throws no accessibility violations', (done) => {
    const html = shallow(PathfinderToday, {
      propsData: {
        items: pathfinderLinks,
      },
    }).html();
    // pass anything that outputs html to axe
    return axe(html).then((response) => {
      expect(response).toHaveNoViolations();
      done();
    });
  });
});
```

2021-05-10 04:04 UTC, gepifanio approved these changes

2021-05-11 02:10 UTC, jaredh-um commented
A few more refinements:
- instead of just pausing on `mouseout`, should also return video to 0 (start)
- when autoplay finishes for the first time, should also return to 0 and pause
- should only autoplay when in viewport - eg; needs to be fixed in Firefox

2021-05-12 00:13 UTC, anormand requested changes
1. Button focus

Problem
- After pressing the close button, focus stays on the close button

Remedy
- After pressing the close button, move focus back to the play button

2. Storybook documentation

We need to included the expected screen reader announcement in the Storybook documentation (see below).

<h4>Screen reader announcement (Voiceover)</h4>

Play button
- Play video [Video label 2m 24s], button

Close button
- Close video, button

2021-05-12 04:15 UTC, anormand commented
Video component now works, but Storybook documentation still needs to be updated

2021-05-12 04:42 UTC, anormand commented
Now passes accessibility checks

2021-05-12 04:44 UTC, merged