feat(component): card article / large / list
unimelb/pattern-lib pull request #1627
Opened 2021-05-20 02:10 UTC by gepifanio

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue number)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] Make sure to do not repeat yourself (DRY)
- [ ] Snapshots tested
- [ ] A11y tested
- [ ] CSS utilises BEM naming convention and structure
- [ ] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [ ] Crossbrowser testing (IE11, Safari 8+, iOS 8.4+, Android 4.4+, Firefox ESR (v52.x), iPhone (4s,6), iPad 2, Galaxy s5) 
- [ ] My changes generate no new warnings
- [ ] I have added tests (e2e and unit) that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Added the new component to the index.js (Vue and Lib) export

# Reviewer Checklist

- [ ] Code is not repeated (DRY)
- [ ] ES6+ code is used where possible
- [ ] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [ ] CSS utilises BEM naming convention and structure
- [ ] Snapshots tested against a copy of dev snapshots to check UI changes are intended
- [ ] A11y tested
- [ ] Crossbrowser tested in at least IE11

2021-05-20 02:12 UTC, gepifanio commented
Comment: Deploy Started

Building with commit ef6a01161dfac25221d89d044427add469f1faaa

https://app.netlify.com/sites/pattern-lib-unimelb/deploys/60a5c508e5ccdb0007a742ec

2021-05-20 04:45 UTC, lmounsey approved these changes
Looks good! I just made one minor tweak to the type size helper

2021-05-20 04:48 UTC, jaredhenderson requested changes
Proper example text required for stories so we can assess if the component is working properly.

2021-05-20 04:48 UTC, jaredhenderson commented on components/today/stories/Cards/CardArticle.vue
> +    category="test category" />
- [ ] Adjust 'test category' text in stories to use proper case, eg; 'Test category'. Otherwise this may resemble a CSS text-transform issue

2021-05-20 04:48 UTC, jaredhenderson commented on components/today/stories/Cards/CardArticleLarge.md
> +    description="Test description"
- [ ] Include a longer description that matches a real use-case so we can see how text is wrapping and behaving properly. Two words is not enough for this

2021-05-20 04:48 UTC, jaredhenderson commented on components/today/stories/Cards/CardArticleLarge.md
> +    :img="{ src: 'https://picsum.photos/seed/1/540/360', alt: 'test alt' }">
- [ ] Use proper case for alt text

2021-05-20 22:44 UTC, jaredhenderson approved these changes
👍

2021-05-24 04:05 UTC, anormand commented
Looks OK and passes testing in both Siteimprove and SortSite

2021-05-24 04:07 UTC, anormand approved these changes

2021-05-24 04:11 UTC, jaredhenderson reviewed
- [ ] @lmounsey Hey Lucas, just checking on the category label colours - they appear to be using a lighter grey than the designs seem to indicate... same with the paragraph text. There's actually some inconsistency in use of the greys in the designs as well, so just wondering if you could clarify what the pattern is here... (checking homepage Figma file - `version 1.4` page and `content iteration` page)

2021-05-24 05:13 UTC, lmounsey commented
@jaredhenderson I think may have changed after our global colour changes (to that mid grey)

Let me confirm with Jacob about this, because if it needs to be the dark grey it should probably be a global shift again

Apologies for this - I don't think it should hold up this component though as we won't directly specific a text colour for these - it should inherit global text colour

2021-05-24 05:17 UTC, gepifanio commented
@lmounsey and @jaredhenderson I will be merging as colours will be treated as global.

2021-05-24 05:17 UTC, merged

2021-05-24 05:19 UTC, lmounsey commented
Hey @jaredhenderson - on closer inspection looks like they are set to 80% pass through - I'm not sure what that equivalent is to try convert it to RGB, but it is indeed lighter than the heading text.

2021-05-24 22:46 UTC, jaredhenderson commented
Hey @lmounsey, you're right about the transparency. Just converted it to a flat colour in Figma and the equivalent is `rgb(74,74,74)` or `#4a4a4a` (`--grey-mid-2`). It looks like those labels are currently using `--grey-mid-1` so they just need to be adjusted from that.