feat(component): Card flat and card flat list
unimelb/pattern-lib pull request #1628
Opened 2021-05-20 05:45 UTC by gepifanio

# Description

Fixes https://todaydesign.atlassian.net/browse/UOM17-121

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

# Checklist:

- [ ] Make sure to do not repeat yourself (DRY)
- [ ] Snapshots tested
- [ ] A11y tested
- [ ] CSS utilises BEM naming convention and structure
- [ ] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [ ] Crossbrowser testing (IE11, Safari 8+, iOS 8.4+, Android 4.4+, Firefox ESR (v52.x), iPhone (4s,6), iPad 2, Galaxy s5) 
- [ ] My changes generate no new warnings
- [ ] I have added tests (e2e and unit) that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Added the new component to the index.js (Vue and Lib) export

# Reviewer Checklist

- [ ] Code is not repeated (DRY)
- [ ] ES6+ code is used where possible
- [ ] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [ ] CSS utilises BEM naming convention and structure
- [ ] Snapshots tested against a copy of dev snapshots to check UI changes are intended
- [ ] A11y tested
- [ ] Crossbrowser tested in at least IE11

2021-05-20 05:48 UTC, gepifanio commented
Comment: Deploy Started

Building with commit 2832ab1126021f5b957eebf2f0f20a505a5eff17

https://app.netlify.com/sites/pattern-lib-unimelb/deploys/60a5f7889d122d0007f3e66a

2021-05-20 07:27 UTC, lmounsey approved these changes
Looks good to me! 

I just made a small tweak to responsive styles on the card list. I've also added a new section to documentation to compliment the home page if you guys use it in the future for other Matrix sites

2021-05-20 23:05 UTC, jaredhenderson requested changes

2021-05-20 23:05 UTC, jaredhenderson commented on components/today/stories/Cards/CardFlatList.vue
> +<template>
- [ ] Please use realistic example data for stories. Having the exact same heading and description lengths (and image) does not give us an accurate demonstration of this component for assessment.

2021-05-20 23:05 UTC, jaredhenderson commented on components/cards/CardFlat.vue
> +  props: {
- [ ] Are images compulsory for this component (don't appear to be)? What happens to the layout if an image is not supplied? Should there be a story showing this usage?

2021-05-24 04:10 UTC, anormand approved these changes
Looks OK and passes testing in both Siteimprove and SortSite

2021-05-24 04:22 UTC, jaredhenderson commented
- Looks fine, pending typography colour questions from other card issue (Figma design is using darker fonts for paragraph, etc.)

2021-05-24 05:20 UTC, gepifanio commented
@jaredhenderson @lmounsey merging this one, as the colours will be globally changed if needed.

2021-05-24 05:23 UTC, merged