Fix/css for today sections
unimelb/pattern-lib pull request #1675
Opened 2021-06-24 00:54 UTC by gepifanio

# Description

Fixes https://todaydesign.atlassian.net/browse/UOM18B-217

- 

# Checklist:

- [ ] Make sure to do not repeat yourself (DRY)
- [ ] Snapshots tested
- [ ] A11y tested
- [ ] CSS utilises BEM naming convention and structure
- [ ] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [ ] Crossbrowser testing (Safari 8+, iOS 8.4+, Android 4.4+, Firefox ESR (v52.x), iPhone (4s,6), iPad 2, Galaxy s5) 
- [ ] My changes generate no new warnings
- [ ] I have added tests (e2e and unit) that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] Added the new component to the index.js (Vue and Lib) export

# Reviewer Checklist

- [ ] Code is not repeated (DRY)
- [ ] ES6+ code is used where possible
- [ ] Code does not mutate variables/objects/arrays but instead uses `map`, `filter` etc to return a new array/object
- [ ] CSS utilises BEM naming convention and structure
- [ ] Snapshots tested against a copy of dev snapshots to check UI changes are intended
- [ ] A11y tested
- [ ] Crossbrowser tested in at least IE11

2021-06-24 01:48 UTC, angieraj commented
Thanks @gepifanio 

1. Standard - Looks good on smaller break points
2. Standard with Image - Looks good on smaller break points
3. 3 up - Starts to get a little crunched between 805px width and 605px width. Not sure this is an issue though. Thoughts @jaredhenderson 
4. Columns - Looks good on smaller break points
5. Testimonial - Image looks quite big on 581px width and 482px width, again will defer to @jaredhenderson on this 
6. Testimonials Long - Looks good on smaller break points
7. Testimonials video - Looks good on smaller break points
8. Bordered - Looks good on smaller break points
9. Card article large - Looks good on smaller break points

2021-06-24 01:57 UTC, jaredhenderson commented on components/section/_section-alt.css
>      position: relative;
✅

2021-06-24 02:31 UTC, jaredhenderson requested changes
Current CSS changes look good, but there could be some refinements to related parts of these components pertaining to breakpoints:
- 3 up - agreed @angieraj that these look a little squashed at the lower end of the breakpoints before switching to single column. However this is part of the base grid system and widely used by many other components, so I can't suggest a quick fix here. Would need a comprehensive review of impact and changes required

- [x] Testimonial - agreed, image is too big when changing to single column and is not restrained in width until the 480px breakpoint - adjust the image width restraint to match the column breakpoint change
<img width="958" alt="Screen Shot 2021-06-24 at 12 14 09 pm" src="https://user-images.githubusercontent.com/34703139/123193023-5e538d80-d4e7-11eb-9daf-bdd942a2dac5.png">

- Testimonial video - @angieraj I hadn't noticed that the behaviour for this one was to scroll off the edge on mobile? Was that the intention? Again, I can't find any reference to the intended design in Figma
<img width="788" alt="Screen Shot 2021-06-24 at 12 16 25 pm" src="https://user-images.githubusercontent.com/34703139/123193194-ad99be00-d4e7-11eb-85fc-999b0652b3e4.png">

- [ ] Card article large changes to single column too soon, resulting in a huge picture from 768px to 600px. Can we adjust the column change breakpoint to 599px to see what that looks like
<img width="1167" alt="Screen Shot 2021-06-24 at 12 20 28 pm" src="https://user-images.githubusercontent.com/34703139/123193334-f2bdf000-d4e7-11eb-8350-650f6e40b3c1.png">

2021-06-24 02:31 UTC, jaredhenderson commented on components/testimonials/_testimonials-alt.css
> +    max-width: 20rem;
✅

2021-06-24 02:31 UTC, jaredhenderson commented on components/testimonials/_testimonials-alt.css
> +    @media (--bp-desktop) {
✅

2021-06-24 02:31 UTC, jaredhenderson commented on components/_utils.css
> +  @media (--bp-desktop) {
✅

2021-06-24 03:49 UTC, angieraj commented
@jaredhenderson with the testimonial video, I believe this is intentional and was part of the template that Lucas built, will need to double check it with him. 

Jacob sent across the Figma link https://www.figma.com/file/yK135x6z5006Y7m6y2pT7H/UoM-18-Study?node-id=3442%3A35934

However it doesn't seem to have any reference to mobile versions of the testimonial video or the accordions.

2021-06-24 04:15 UTC, angieraj commented
@jaredhenderson and @gepifanio Just wanted to flag something on 

1. Study Header [https://deploy-preview-1675--pattern-lib-unimelb.netlify.app/?utm_source=github&utm_campaign=bot_dp&selectedKind=Today%2FHeader&selectedStory=Study&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel](url)
2. [Pathfinder Slot ](https://deploy-preview-1675--pattern-lib-unimelb.netlify.app/?utm_source=github&utm_campaign=bot_dp&selectedKind=Today%2FPathfinder&selectedStory=Slot&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)

On my iPhone 11, the magnifying glass next to the input field seems to be separated from the input field. Using the responsive tool on chrome it looks fine but this is what I'm seeing. 

![Home - The University of Melbourne](https://user-images.githubusercontent.com/47799409/123201679-81d20480-d4f6-11eb-933c-c6dfa4e46cd9.png)
![IMG_3035](https://user-images.githubusercontent.com/47799409/123201693-8991a900-d4f6-11eb-9a29-f89239273f83.PNG)

Can we please investigate and fix that?

2021-06-24 04:23 UTC, jaredhenderson commented
@angieraj as discussed, we will address the search box "rounded" issue separately from this one if you wouldn't mind making a ticket for it

2021-06-24 04:46 UTC, jaredhenderson requested changes

2021-06-24 04:46 UTC, jaredhenderson commented on components/testimonials/_testimonials-alt.css
> -    @media (--bp-max-mobile) {
- This one needs to come in at the 599px breakpoint, not be deleted

2021-06-25 00:21 UTC, jaredhenderson requested changes

2021-06-25 00:21 UTC, jaredhenderson commented on components/testimonials/_testimonials-alt.css
> -    @media (--bp-max-mobile) {
Not **above** 599px, **below**. We're talking about the display on mobile

2021-06-25 00:21 UTC, jaredhenderson commented on components/cards/_card-article-large.css
> +    @media (--bp-x-tablet) {
This is behaving really weirdly when resizing now. Row should change to column at 599px only

2021-06-25 00:43 UTC, jaredhenderson requested changes
Ok, `card article large` doesn't work well changing at 599px (the text column is too tall compared to the image) - can you please revert the changes to `_card-article-large.css` and we'll just leave it as it was

2021-06-25 01:00 UTC, jaredhenderson approved these changes

2021-06-25 01:10 UTC, merged